version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of your requirements.txt or pyproject.toml
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"