version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of your requirements.txt or pyproject.toml
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*" # Placeholder to satisfy Dependabot schema
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
