site_name: SynTechRev-PolyCodCal Docs
repo_url: https://github.com/SynTechRev/SynTechRev-PolyCodCal
nav:
  - Home: index.md
  - Guides:
    - Phase 6 Ingestion: docs/PHASE6_INGESTION.md
    - Development Workflow: docs/DEVELOPMENT_WORKFLOW.md
  - Reference:
    - README: README.md
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
