site_name: SynTechRev-PolyCodCal Docs
repo_url: https://github.com/SynTechRev/SynTechRev-PolyCodCal
nav:
  - Home: index.md
  - Guides:
    - Phase 6 Ingestion: PHASE6_INGESTION.md
    - Development Workflow: DEVELOPMENT_WORKFLOW.md
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
