name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel
        run: |
          python -m build

      - name: Publish to TestPyPI (skip if secret missing)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          if [ -z "${TWINE_PASSWORD:-}" ]; then
            echo "Skipping TestPyPI publish: TEST_PYPI_API_TOKEN not set"
            exit 0
          fi
          python -m twine upload \
            --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Publish to PyPI (skip if secret missing)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ -z "${TWINE_PASSWORD:-}" ]; then
            echo "Skipping PyPI publish: PYPI_API_TOKEN not set"
            exit 0
          fi
          python -m twine upload dist/*
